env:
  - CGO_ENABLED=0
builds:
  - id: eqbc-go
    main: ./cmd/eqbc
    binary: eqbc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

archives:
  - id: all
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
